<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Connectors/connectors/sources/ext/rest/insideview/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$connector_strings = array ( 
   'LBL_GET_STARTED' => 'Başla!' ,
   'LBL_TOS0' => 'InsideView&#39;i kabul ediyorum ' ,
   'LBL_TOS1' => 'Kullanım Koşulları' ,
   'LBL_TOS3' => 'Gizlilik Politikası' ,
   'iv_description0' => '"Başla" butonuna tıklayarak InsideView kullanım şartlarını kabul etmiş oluyorsunuz' ,
   'LBL_OPP' => 'Fırsatları Bul' ,
   'LBL_OPP_SUB' => 'müşterilere ulaşmak için' ,
   'LBL_REFERRAL' => 'Referansları Alın' ,
   'LBL_REFERRAL_SUB' => 'anahtar karar üreticileri için' ,
   'LBL_ENGAGE' => 'Müşterileri Bağla' ,
   'LBL_ENGAGE_SUB' => 'etkileşim ile başlayanlar' );

?>
