<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Connectors/connectors/sources/ext/eapm/facebook/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$connector_strings = array ( 
   'LBL_LICENSING_INFO' => '<table border="0" cellspacing="1"><tr><td valign="top" width="35%" class="dataLabel">Sugar kurulumunuzu Facebook&#169; ağına yeni bir uygulama olarak kaydederek, API Anahtarı Ve Uygulama Şifresi elde edin.<br/><br>Kurulumunuz için uygulama tanımlama adımları:<br/><br/><ol><li>Uygulama tanımlamak için Facebook&#169; adresine gidin: <a href="http://www.facebook.com/developers/createapp.php" target="_blank">http://www.facebook.com/developers/createapp.php</a>.</li><li>Uygulamayı kaydetmek istediğiniz Facebook&#169; hesabıyla giriş yapın.</li><li>"Uygulama Oluştur" sayfasında, uygulama ismini giriniz. Bu adres, kullanıcıların kendi Facebook&#169; hesaplarını Sugar içinden otantike ettiklerinde görecekleri isimdir.</li><li>Facebook&#169; kullanım şartlarını kabul edin.</li><li>"Uygulama Oluştur" adresini tıklayınız</li><li>Güvenlik kontrolünü geçmek için kelimeleri girin.</li><li>Uygulama sayfanızda, "Web Sitesi" alanına gidin (soldaki menüde yer almaktadır) ve Sugar kurulumunuza ait lokal URL adresini "Site URL" adresine giriniz.</li><li>"Değişiklikleri Kaydet" butonuna tıklayınız</li><li>"Facebook Entegrasyon" sayfasına gidin (soldaki menüde yer almaktadır) ve API Anahtarı ve Uygulama Şifresini bulun. Uygulama ID ve Uygulama Şifresini aşağıya girin.</li></ol></td></tr></table>' ,
   'oauth_consumer_key' => 'API Anahtar' ,
   'oauth_consumer_secret' => 'Uygulama Şifresi' );

?>
